# Generated by Django 4.2.7 on 2026-09-10 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_canonico', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Classe',
                'verbose_name_plural': 'Classes',
                'ordering': ['nome_canonico'],
            },
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('quantidade_imagens', models.PositiveIntegerField(default=0)),
                ('anotacoes', models.FileField(upload_to='datasets/anotacoes/')),
                ('split', models.CharField(choices=[('train', 'Train'), ('valid', 'Valid'), ('test', 'Test')], default='train', max_length=10)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('classes_cobertas', models.ManyToManyField(related_name='datasets', to='app.classe')),
            ],
            options={
                'verbose_name': 'Dataset',
                'verbose_name_plural': 'Datasets',
                'ordering': ['-data_cadastro'],
            },
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('origem', models.CharField(choices=[('reutilizado', 'Reutilizado'), ('treinado', 'Treinado')], max_length=20)),
                ('acuracia_geral', models.FloatField(blank=True, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('classes_suportadas', models.ManyToManyField(related_name='modelos', to='app.classe')),
            ],
            options={
                'verbose_name': 'Modelo',
                'verbose_name_plural': 'Modelos (Registry)',
                'ordering': ['-data_cadastro'],
            },
        ),
        migrations.CreateModel(
            name='Treinamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo_base', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('em_andamento', 'Em andamento'), ('concluido', 'Concluído'), ('falhou', 'Falhou')], default='em_andamento', max_length=20)),
                ('epocas', models.PositiveIntegerField()),
                ('batch_size', models.PositiveIntegerField()),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='treinamentos', to='app.dataset')),
                ('modelo_resultante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treinamento_origem', to='app.modelo')),
            ],
            options={
                'verbose_name': 'Treinamento',
                'verbose_name_plural': 'Treinamentos',
                'ordering': ['-data_cadastro'],
            },
        ),
        migrations.CreateModel(
            name='SinonimoClasse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termo_sinonimo', models.CharField(max_length=100, unique=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sinonimos', to='app.classe')),
            ],
            options={
                'verbose_name': 'Sinônimo de Classe',
                'verbose_name_plural': 'Dicionário de Sinônimos',
                'ordering': ['-data_cadastro'],
            },
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('verificando', 'Verificando conhecimento'), ('aguardando_dataset', 'Aguardando dataset'), ('treinando', 'Treinando'), ('pronto', 'Pronto')], default='rascunho', max_length=30)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('classes_desejadas', models.ManyToManyField(related_name='projetos', to='app.classe')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projetos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
                'ordering': ['-data_cadastro'],
            },
        ),
        migrations.CreateModel(
            name='Metrica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escopo', models.CharField(choices=[('modelo', 'Modelo'), ('execucao', 'Execução')], max_length=20)),
                ('tipo', models.CharField(max_length=50)),
                ('valor', models.FloatField()),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('modelo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metricas', to='app.modelo')),
                ('treinamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metricas', to='app.treinamento')),
            ],
            options={
                'verbose_name': 'Métrica',
                'verbose_name_plural': 'Métricas',
                'ordering': ['-data_cadastro'],
            },
        ),
        migrations.CreateModel(
            name='Inferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem_entrada', models.ImageField(upload_to='inferencias/entrada/')),
                ('caixas_detectadas', models.JSONField(default=list)),
                ('confianca_media', models.FloatField(blank=True, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('modelos_usados', models.ManyToManyField(related_name='inferencias', to='app.modelo')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inferencias', to='app.projeto')),
            ],
            options={
                'verbose_name': 'Inferência',
                'verbose_name_plural': 'Inferências',
                'ordering': ['-data_cadastro'],
            },
        ),
        migrations.CreateModel(
            name='EstrategiaComposicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estrategia', models.CharField(choices=[('reuso_exato', 'Reuso exato'), ('reuso_parcial', 'Reuso parcial'), ('vocabulario_aberto', 'Vocabulário aberto'), ('treino', 'Treino')], max_length=30)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estrategias', to='app.classe')),
                ('modelos_envolvidos', models.ManyToManyField(blank=True, related_name='estrategias', to='app.modelo')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estrategias', to='app.projeto')),
            ],
            options={
                'verbose_name': 'Estratégia de Composição',
                'verbose_name_plural': 'Estratégias de Composição',
                'ordering': ['-data_cadastro'],
            },
        ),
        migrations.AddField(
            model_name='dataset',
            name='projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to='app.projeto'),
        ),
    ]
